<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 7 - table "messenger_messages" (config/packages/messenger.yaml, transport
 * "failed" : 'doctrine://default?queue_name=failed' - dead-letter PostgreSQL, jamais Redis,
 * cohérent avec backend/CLAUDE.md section 10). Schéma repris exactement de
 * Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection (vendor/symfony/
 * doctrine-messenger, vérifié sur la version installée au moment de l'implémentation) plutôt
 * que laissé à la commande `messenger:setup-transports` au runtime, pour rester cohérent
 * avec la règle du projet : toute modification de schéma passe par une migration
 * (backend/CLAUDE.md, section 7).
 */
final class Version20260820100001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 7 - messenger_messages (transport "failed", dead-letter Messenger).';
    }

    public function up(Schema $schema): void
    {
        // "GENERATED BY DEFAULT AS IDENTITY" (pas BIGSERIAL) : syntaxe exacte attendue par
        // Doctrine DBAL pour une colonne autoincrémentée sur cette version (vérifié via
        // `doctrine:schema:validate` au moment de l'implémentation - BIGSERIAL est
        // fonctionnellement équivalent mais crée une dérive de schéma détectée à chaque
        // validation).
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_messenger_messages_queue ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
